export { CheckBoxes } from "./CheckBoxes";
export { Date } from "./Date";
export { DropDown } from "./DropDown";
export { FileLoad } from "./Fileload";
export { LinearScale } from "./LinearScale";
export { MultiChoiceGrid } from "./MultiChoiceGrid";
export const MultiCoices = "./MultiChoices";
export const Paragraph = "./Paragraph";
export const ShortAnswer = "./ShortAnswer";
export { TickBoxGrid } from "./TickBoxGrid";
export { Time } from "./Time";
